### ISSUE TITLE
Wolken achtergrond

### ISSUE THREAD

**Issue by JalalToufik** [mcphendriks/connect-your-tribe-squad-page#3]
Als je de wolkjes in je achtergrond wilt animeren zou ik beter een achtergrond zonder wolkjes gebruiken en dan vervolgens per student een nieuwe afbeelding/svg van een wolk als achtergrond gebruiken. hierdoor kan je ze ook beter positioneren en animeren naar keuze!

**Comment by mcphendriks** [comment]
Fixed: issues opgelost door nth-child(2n) te gebruiken om te positioneren. 
Afbeelding (<img> tag) in de html geïmplementeerd.
