### ISSUE TITLE
Consistentie lettertype

### ISSUE THREAD

**Issue by JalalToufik** [mcphendriks/connect-your-tribe-squad-page#7]
Het viel me op dat je op de button een lichtere lettertype gebruikt. Je zou hier misschien beter de ze zelfde letterdikte kunnen gebruiken.

![image](https://user-images.githubusercontent.com/112856590/219616171-2d9e6f0e-3f4e-4650-b53c-1ac5ea5b92b5.png)

**Comment by mcphendriks** [comment]
fix: fix consistentie lettertype bold
